# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d040aa3747e924b9082678e2484e7c5f0dae12b3fc4b6fab279893b8e8d51ffb9646027cd8de3f54472d2dbcd5e31463b58a32a915eb97cfab6d16da5f69f7d9

test:
  secret_key_base: ec8fab1c2a78db6d1ef0ea674209350feb6855a321769df59dfc40d2cc83e0df264534428020466c526ec6268a63553da586489e115a2ca6a02b7f61460d77a6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
